### ISSUE TITLE
当配置项为不循环播放时，依旧会循环播放

### ISSUE THREAD

**Issue by ch656409110** [copthuy/jSlider#1]
你好，修复了一个bug，当配置项为不循环播放时，依旧会循环播放，
我的修改如下：

`
				if (isLoaded) {
                    //修改bug：当loop为false时候，增量为0
				    if (settings.loop == false) {
				        $slider.sliderGo(0);
				    } else {
				        $slider.sliderGo(1);
				    }
				}

`

**Comment by copthuy** [comment]
jSlider is now _carousel
